[target.wasm32-unknown-unknown]
rustflags = '-C link-arg=--allow-undefined --cfg getrandom_backend="wasm_js"'

[env]
CC = "/opt/homebrew/opt/llvm/bin/clang"
CFLAGS = "--sysroot=/opt/homebrew/Cellar/wasi-libc/32/share/wasi-sysroot"
