import { z } from "zod";
import type { JsCallSpec } from "./manifest.js";
import * as schemas from "../schemas.js";

export type ContentScriptToolSpec<P = unknown, R = unknown> = Omit<
	JsCallSpec<P, R>,
	"owner" | "handler"
> & {
	handlerKey: string;
};

/** Static build-time list of content-script tool specs.
 *  Both main-thread and content-script IIFE bundles import this at build time.
 *  Populated in wu-7/wu-8 when page.ts and tab.ts are migrated.
 *
 *  TODO: Mutation returnDoc strings are hand-written pseudo-type-signatures.
 *  When PageActionResultSchema changes, update all mutation returnDoc strings
 *  to match, or generate them from the schema shape to eliminate drift. */
export const CONTENT_SCRIPT_TOOL_SPECS: readonly ContentScriptToolSpec[] = [
	{
		action: "page_back",
		namespace: "page",
		name: "back",
		description: "Go back in the active tab",
		params: schemas.PageBackParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [],
		returnDoc: "Navigation result",
		errorCode: "E_NO_TAB",
		example: "page.back()",
		handlerKey: "back",
	},
	{
		action: "page_click",
		namespace: "page",
		name: "click",
		description: "Click an element in the active tab",
		params: schemas.PageClickParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label to click (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'click', refId? }",
		errorCode: "E_MISSING_PARAM",
		example: 'page.click({ refId: "e2" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.click"],
		},
		handlerKey: "click",
	},
	{
		action: "page_fill",
		namespace: "page",
		name: "fill",
		description: "Fill an element in the active tab",
		params: schemas.PageFillParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "value",
				type: "string",
				required: false,
				description: "Value to fill (literal)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'fill', refId?, value? }",
		errorCode: "E_MISSING_PARAM",
		example: 'page.fill({ refId: "e2", value: "hello" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.fill"],
		},
		handlerKey: "fill",
	},
	{
		action: "page_type",
		namespace: "page",
		name: "type",
		description: "Type into an element in the active tab",
		params: schemas.PageTypeParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "text",
				type: "string",
				required: false,
				description: "Text to type (literal)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'type', refId?, value? }",
		errorCode: "E_MISSING_PARAM",
		example: 'page.type({ refId: "e2", text: "hello" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.type"],
		},
		handlerKey: "type",
	},
	{
		action: "page_append",
		namespace: "page",
		name: "append",
		description: "Append text to an element in the active tab",
		params: schemas.PageAppendParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "text",
				type: "string",
				required: false,
				description: "Text to append (literal)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'append', refId?, value? }",
		errorCode: "E_MISSING_PARAM",
		example: 'page.append({ refId: "e2", text: " world" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
		},
		handlerKey: "append",
	},
	{
		action: "page_press",
		namespace: "page",
		name: "press",
		description: "Press a key in the active tab",
		params: schemas.PagePressParamsSchema,
		returns: schemas.PageActionResultSchema,
		fields: ["key"],
		paramTypes: [
			{
				name: "key",
				type: "string",
				required: true,
				description: "Key to press (literal)",
			},
		],
		returnDoc: "{ ok: true, action: 'press', key? }",
		errorCode: "E_NO_TAB",
		example: 'page.press("Enter")',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.press"],
		},
		handlerKey: "press",
	},
	{
		action: "page_select",
		namespace: "page",
		name: "select",
		description: "Select an option in the active tab",
		params: schemas.PageSelectParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
			{
				name: "value",
				type: "string",
				required: false,
				description: "Option value to select (literal)",
			},
		],
		returnDoc: "{ ok: true, action: 'select', refId?, value? }",
		errorCode: "E_MISSING_PARAM",
		example: 'page.select({ refId: "e2", value: "option1" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.select"],
		},
		handlerKey: "select",
	},
	{
		action: "page_check",
		namespace: "page",
		name: "check",
		description: "Check/uncheck an element in the active tab",
		params: schemas.PageCheckParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
			{
				name: "checked",
				type: "boolean",
				required: false,
				description: "Whether to check or uncheck (literal)",
			},
		],
		returnDoc: "{ ok: true, action: 'check', refId?, checked? }",
		errorCode: "E_MISSING_PARAM",
		example: 'page.check({ refId: "e2", checked: true })',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.check"],
		},
		handlerKey: "check",
	},
	{
		action: "page_hover",
		namespace: "page",
		name: "hover",
		description: "Hover over an element in the active tab",
		params: schemas.PageHoverParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'hover', refId? }",
		errorCode: "E_MISSING_PARAM",
		example: 'page.hover({ refId: "e2" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.hover"],
		},
		handlerKey: "hover",
	},
	{
		action: "page_unhover",
		namespace: "page",
		name: "unhover",
		description: "Unhover in the active tab",
		params: schemas.PageUnhoverParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [],
		returnDoc: "{ ok: true, action: 'unhover' }",
		errorCode: "E_NO_TAB",
		example: "page.unhover()",
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.unhover"],
		},
		handlerKey: "unhover",
	},
	{
		action: "page_scroll",
		namespace: "page",
		name: "scroll",
		description: "Scroll the active tab",
		params: schemas.PageScrollParamsSchema,
		returns: schemas.PageActionResultSchema,
		fields: ["direction", "amount"],
		paramTypes: [
			{
				name: "direction",
				type: "string",
				required: false,
				description: "Scroll direction (up or down) (literal)",
			},
			{
				name: "amount",
				type: "number",
				required: false,
				description: "Scroll amount in pixels (literal)",
			},
		],
		returnDoc: "Scroll result",
		errorCode: "E_NO_TAB",
		example: 'page.scroll("down", 500)',
		handlerKey: "scroll",
	},
	{
		action: "page_scroll_to",
		namespace: "page",
		name: "scroll_to",
		description: "Scroll to an element in the active tab",
		params: schemas.PageScrollToParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID to scroll to (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label to scroll to (label)",
			},
		],
		returnDoc: "Scroll to result",
		errorCode: "E_MISSING_PARAM",
		example: 'page.scroll_to({ refId: "e2" })',
		handlerKey: "scroll_to",
	},
	{
		action: "page_dblclick",
		namespace: "page",
		name: "dblclick",
		description: "Double-click an element in the active tab",
		params: schemas.PageDblClickParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'dblclick', refId? }",
		errorCode: "E_MISSING_PARAM",
		example: 'page.dblclick({ refId: "e2" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab is active and the content script is ready before mutating"],
			notes: [
				"Same content-script path as web.tab.*",
				"Always operates on the active tab; use web.tab.* if you need to target a specific tabId",
			],
			tags: ["mutation", "write"],
			relatedApis: ["web.tab.dblclick"],
		},
		handlerKey: "dblclick",
	},
	{
		action: "tab_click",
		namespace: "web.tab",
		name: "click",
		description: "Click in a tab",
		params: schemas.TabClickParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'click', refId? }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.click({ tabId: 123, refId: "e2" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.click"],
		},
		handlerKey: "click",
	},
	{
		action: "tab_fill",
		namespace: "web.tab",
		name: "fill",
		description: "Fill in a tab",
		params: schemas.TabFillParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "value",
				type: "string",
				required: false,
				description: "Value to fill (literal)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'fill', refId?, value? }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.fill({ tabId: 123, refId: "e2", value: "hello" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.fill"],
		},
		handlerKey: "fill",
	},
	{
		action: "tab_scroll_to",
		namespace: "web.tab",
		name: "scroll_to",
		description: "Scroll to position in a tab",
		params: schemas.TabScrollToParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{ name: "x", type: "number", required: false, description: "X coordinate (literal)" },
			{ name: "y", type: "number", required: false, description: "Y coordinate (literal)" },
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "Scroll to result",
		errorCode: "E_NO_TAB",
		example: 'web.tab.scroll_to({ tabId: 123, refId: "e2" })',
		handlerKey: "scroll_to",
	},
	{
		action: "tab_type",
		namespace: "web.tab",
		name: "type",
		description: "Type in a tab",
		params: schemas.TabTypeParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "text",
				type: "string",
				required: false,
				description: "Text to type (literal)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'type', refId?, value? }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.type({ tabId: 123, refId: "e2", text: "hello" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.type"],
		},
		handlerKey: "type",
	},
	{
		action: "tab_press",
		namespace: "web.tab",
		name: "press",
		description: "Press a key in a tab",
		params: schemas.TabPressParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "key",
				type: "string",
				required: false,
				description: "Key to press (literal)",
			},
		],
		returnDoc: "{ ok: true, action: 'press', key? }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.press({ tabId: 123, key: "Enter" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.press"],
		},
		handlerKey: "press",
	},
	{
		action: "tab_select",
		namespace: "web.tab",
		name: "select",
		description: "Select an option in a tab",
		params: schemas.TabSelectParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
			{
				name: "value",
				type: "string",
				required: false,
				description: "Option value to select (literal)",
			},
		],
		returnDoc: "{ ok: true, action: 'select', refId?, value? }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.select({ tabId: 123, refId: "e2", value: "option1" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.select"],
		},
		handlerKey: "select",
	},
	{
		action: "tab_check",
		namespace: "web.tab",
		name: "check",
		description: "Check/uncheck in a tab",
		params: schemas.TabCheckParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
			{
				name: "checked",
				type: "boolean",
				required: false,
				description: "Whether to check or uncheck (literal)",
			},
		],
		returnDoc: "{ ok: true, action: 'check', refId?, checked? }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.check({ tabId: 123, refId: "e2", checked: true })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.check"],
		},
		handlerKey: "check",
	},
	{
		action: "tab_hover",
		namespace: "web.tab",
		name: "hover",
		description: "Hover in a tab",
		params: schemas.TabHoverParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'hover', refId? }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.hover({ tabId: 123, refId: "e2" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.hover"],
		},
		handlerKey: "hover",
	},
	{
		action: "tab_unhover",
		namespace: "web.tab",
		name: "unhover",
		description: "Unhover in a tab",
		params: schemas.TabUnhoverParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
		],
		returnDoc: "{ ok: true, action: 'unhover' }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.unhover({ tabId: 123 })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.unhover"],
		},
		handlerKey: "unhover",
	},
	{
		action: "tab_scroll",
		namespace: "web.tab",
		name: "scroll",
		description: "Scroll in a tab",
		params: schemas.TabScrollParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "direction",
				type: "string",
				required: false,
				description: "Scroll direction (up or down) (literal)",
			},
			{
				name: "amount",
				type: "number",
				required: false,
				description: "Scroll amount in pixels (literal)",
			},
		],
		returnDoc: "Scroll result",
		errorCode: "E_NO_TAB",
		example: 'web.tab.scroll({ tabId: 123, direction: "down", amount: 500 })',
		handlerKey: "scroll",
	},
	{
		action: "tab_dblclick",
		namespace: "web.tab",
		name: "dblclick",
		description: "Double-click in a tab",
		params: schemas.TabDblClickParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
			{
				name: "refId",
				type: "string",
				required: false,
				description: "Element reference ID (refId)",
			},
			{
				name: "label",
				type: "string",
				required: false,
				description: "Element label (label)",
			},
		],
		returnDoc: "{ ok: true, action: 'dblclick', refId? }",
		errorCode: "E_NO_TAB",
		example: 'web.tab.dblclick({ tabId: 123, refId: "e2" })',
		agentMeta: {
			prerequisites: ["Ensure the target tab exists and the content script is ready before mutating"],
			notes: ["Explicit tabId required; same handlers as page.*"],
			tags: ["mutation", "write"],
			relatedApis: ["page.dblclick"],
		},
		handlerKey: "dblclick",
	},
	{
		action: "tab_back",
		namespace: "web.tab",
		name: "back",
		description: "Go back in a tab",
		params: schemas.TabBackParamsSchema,
		returns: schemas.PageActionResultSchema,
		paramTypes: [
			{ name: "tabId", type: "number", required: true, description: "Tab ID (literal)" },
		],
		returnDoc: "Back result",
		errorCode: "E_NO_TAB",
		example: 'web.tab.back({ tabId: 123 })',
		handlerKey: "back",
	},
] as const;
